/** Renders the current system prompt to stdout, so prompts/*.md can be regenerated. */
import { SYSTEM_PROMPT, PROMPT_VERSION } from '../lib/prompt';
console.log(`<!-- Rendered system prompt, ${PROMPT_VERSION}. Generated by scripts/dump-prompt.ts -->\n`);
console.log('```text');
console.log(SYSTEM_PROMPT);
console.log('```');
